# Generated by Django 3.1.7 on 2021-03-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pilot',
            unique_together={('forename', 'surname')},
        ),
    ]
