# Generated by Django 3.1.7 on 2021-03-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0002_auto_20210322_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pilot/<django.db.models.fields.CharField>/'),
        ),
    ]
