# Generated by Django 3.1.7 on 2021-03-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0003_auto_20210322_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='driver_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pilot',
            name='driver_ref',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='forename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='nationality',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='surname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pilot',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
