# Generated by Django 3.1.7 on 2021-03-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0004_auto_20210322_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pilot/'),
        ),
    ]
