# Generated by Django 3.1.7 on 2021-03-28 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilot', '0005_auto_20210323_0949'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pilot',
            unique_together=set(),
        ),
    ]
