# Generated by Django 3.1.7 on 2021-03-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructorSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='constructor/logo/')),
                ('car', models.ImageField(blank=True, null=True, upload_to='constructor/car/')),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructor_season', to='constructor.constructors')),
            ],
        ),
    ]
