# Generated by Django 3.1.7 on 2021-03-29 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pilot', '0006_auto_20210328_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='pilot/season_image/')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_season', to='pilot.pilot')),
            ],
        ),
    ]
